settings:
  accountName: "Example"
  deploymentUid: "ss123456"
  sitecorePrefix: "sitecore"
  solrUsername: ""
  solrPassword: ""
  sitecoreVersion : "10.2.0"              # Supported versions - 9.0.2, 9.1.1, 9.2.0, 9.3.0, 10.0.0, 10.1.0, 10.1.1, 10.2.0, 10.3.0
  isUniqueConfigs: "true"                 # [true/false] 
  configurationMode: "XP"                 # ["XP" "XCONNECT" "XP|XCONNECT"]
  isSxa: "false"                           # Generates two additional search indexes for SXA
