settings:
  accountName: "Example"
  deploymentUid: "ss123456"
  sitecorePrefix: "sitecore"
  solrUsername: ""
  solrPassword: ""
  sitecoreVersion : "10.2.0"              # Supported versions - 9.0.2, 9.1.1, 9.2.0, 9.3.0, 10.0.0, 10.1.0, 10.1.1, 10.2.0, 10.3.0
  isUniqueConfigs: "true"                 # [true/false] 
  configurationMode: "XP"                 # ["XP" "XCONNECT" "XP|XCONNECT"]
  isSxa: "false"                          # Generates two additional search indexes for SXA
  isSwitchOnRebuild: "false"               # Generates an additional search index and its alias for each Solr index
  switchOnRebuild:
    enableForPlatformIndexes: "true"
    enableForMarketingIndexes: "false"
    enableForSXA: "false"
    sufix: "_rebuild"
    mainAlias: "_MainAlias"
    rebuildAlias: "_RebuildAlias"
    sitecorePrefix:  "sitecore"
  customIndexes:
    # - core: "sitecore101-531"
    #   isSwitchOnRebuild: "false"
    # - core: "sitecore102-533"
    #   isSwitchOnRebuild: "false"